security:
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'
    providers:
        app_user_provider:
            entity:
                class: App\Entity\User
                property: email
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            lazy: true
            provider: app_user_provider
            form_login:
                login_path: security_authentication_login
                check_path: security_authentication_login
                enable_csrf: true
            logout:
                path: security_authentication_logout
                target: security_authentication_login

    access_control:
        - { path: ^/admin/, roles: ROLE_USER }
