App\Model\MemberData:
    constraints:
        - Expression:
              expression: 'this.legalRepresentatives or this.getAge() >= 18'
              message: 'member_data.legal_representatives_required_for_children'
    properties:
        birthDate:
            - Range:
                  max: 'yesterday'
        email:
            - NotBlank: ~
            - Email: ~
        firstName:
            - NotBlank: ~
            - Length:
                min: 2
                max: 255
        lastName:
            - NotBlank: ~
            - Length:
                min: 2
                max: 255
        legalRepresentatives:
            - Valid: ~
